const actionTypes = {
  CHANGE_ACTIVE_TAB: 'CONFIG/CHANGE_ACTIVE_TAB',
  CHANGE_PREVIEW_MODE: 'CONFIG/CHANGE_PREVIEW_MODE',
  SET_SELECTED_BLOCK: 'LAYOUT/SET_SELECTED_BLOCK',
  PUSH_BLOCK: 'LAYOUT/PUSH_BLOCK',
  CHANGE_BLOCK_DATA: 'LAYOUT/CHANGE_BLOCK_DATA',
  REORDER_LAYOUT: 'LAYOUT/REORDER_LAYOUT',
  DELETE_BLOCK: 'LAYOUT/DELETE_BLOCK',
  CHANGE_DOCUMENT_ID: 'LAYOUT/CHANGE_DOCUMENT_ID',
};

export default actionTypes;
