const actionTypes = {
  CHANGE_ACTIVE_TAB: 'CONFIG/CHANGE_ACTIVE_TAB',
  CHANGE_PREVIEW_MODE: 'CONFIG/CHANGE_PREVIEW_MODE',
  SET_SELECTED_BLOCK: 'LAYOUT/SET_SELECTED_BLOCK',
  PUSH_BLOCK: 'LAYOUT/PUSH_BLOCK',
  CHANGE_BLOCK_DATA: 'LAYOUT/CHANGE_BLOCK_DATA',
  REORDER_LAYOUT: 'LAYOUT/REORDER_LAYOUT',
  MOVE_BLOCK: 'LAYOUT/MOVE_BLOCK',
  DELETE_BLOCK: 'LAYOUT/DELETE_BLOCK',
  CHANGE_TEMPLATE_ID: 'LAYOUT/CHANGE_TEMPLATE_ID',
  // Page actions
  ADD_PAGE: 'LAYOUT/ADD_PAGE',
  REMOVE_PAGE: 'LAYOUT/REMOVE_PAGE',
  SWITCH_PAGE: 'LAYOUT/SWITCH_PAGE',
  UPDATE_PAGE_NAME: 'LAYOUT/UPDATE_PAGE_NAME',
};

export default actionTypes;
