const actionTypes = {
  CHANGE_ACTIVE_TAB: 'CONFIG/CHANGE_ACTIVE_TAB',
  CHANGE_PREVIEW_MODE: 'CONFIG/CHANGE_PREVIEW_MODE',
  SET_SELECTED_BLOCK: 'LAYOUT/SET_SELECTED_BLOCK',
  PUSH_BLOCK: 'LAYOUT/PUSH_BLOCK',
};

export default actionTypes;
